# Generated by Django 4.0.1 on 2022-02-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_project_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=255)),
            ],
        ),
    ]
