# Generated by Django 4.0.1 on 2022-02-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_youtubevideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
