# Generated by Django 4.0.1 on 2022-02-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_rename_name_project_title_remove_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='project',
        ),
    ]
