# Generated by Django 4.0.1 on 2022-02-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
            ],
        ),
    ]
